// Detect and strip C2PA / AI-related metadata from PNG, JPEG, and WebP
// (stdlib only). Faithful Go port of service/scripts/image_meta.py.
package cleaning

import (
	"bytes"
	"context"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"
	"time"
)

// Magic signatures (mirrors the Python PNG_SIG/JPEG_SOI/WEBP_RIFF/WEBP_SIG).
var (
	pngSig   = []byte("\x89PNG\r\n\x1a\n")
	jpegSOI  = []byte("\xff\xd8")
	webpRIFF = []byte("RIFF")
	webpSIG  = []byte("WEBP")
)

// c2paMarkers lists chunk types / content patterns associated with C2PA / AI
// provenance (mirrors the Python C2PA_MARKERS tuple; values identical).
var c2paMarkers = [][]byte{
	[]byte("c2pa"),
	[]byte("C2PA"),
	[]byte("jumb"),
	[]byte("JUMB"),
	[]byte("c2ma"),
	[]byte("contentcredentials"),
	[]byte("contentauth"),
	[]byte("cai:"),
	[]byte("http://ns.adobe.com/xmp/InstanceID/"), // not solely C2PA
}

// aiMetaHints lists AI provenance content hints (mirrors AI_META_HINTS;
// values identical, including the public generator names / generation-
// parameter signatures added 2026-08). Matching is case-insensitive
// substring over metadata payloads only.
var aiMetaHints = [][]byte{
	[]byte("c2pa"),
	[]byte("C2PA"),
	[]byte("contentcredentials"),
	[]byte("ContentCredentials"),
	[]byte("digitalSourceType"),
	[]byte("trainedAlgorithmicMedia"),
	[]byte("compositeWithTrainedAlgorithmicMedia"),
	[]byte("algorithmicMedia"),
	[]byte("AIGC"),
	[]byte("aigc"),
	[]byte("AI generated"),
	[]byte("Generated by"),
	[]byte("Claude"),
	[]byte("Anthropic"),
	[]byte("OpenAI"),
	[]byte("SynthID"),
	[]byte("dcterms:provenance"),
	// Public generator names / generation-parameter signatures (2026-08).
	[]byte("Midjourney"),
	[]byte("Stable Diffusion"),
	[]byte("stablediffusion"),
	[]byte("Stability AI"),
	[]byte("SDXL"),
	[]byte("ComfyUI"),
	[]byte("Automatic1111"),
	[]byte("Negative prompt:"),
	[]byte("FLUX.1"),
	[]byte("flux1"),
	[]byte("Black Forest Labs"),
	[]byte("Ideogram"),
	[]byte("Recraft"),
	[]byte("Leonardo.ai"),
	[]byte("DALL-E"),
	[]byte("DALL·E"),
	[]byte("gpt-image"),
	[]byte("Imagen"),
	[]byte("Adobe Firefly"),
	[]byte("Grok"),
	// Chinese generators
	[]byte("Doubao"),
	[]byte("豆包"),
	[]byte("Jimeng"),
	[]byte("即梦"),
	[]byte("Dreamina"),
	[]byte("Hunyuan"),
	[]byte("混元"),
	[]byte("Wanx"),
	[]byte("通义万相"),
	[]byte("Kling"),
	[]byte("可灵"),
	[]byte("CogView"),
	[]byte("CogVideoX"),
	[]byte("智谱"),
	[]byte("文心一格"),
	[]byte("ERNIE-ViLG"),
	[]byte("Hailuo"),
	[]byte("海螺"),
	[]byte("Vidu"),
	[]byte("PixVerse"),
	// Music / speech generators
	[]byte("Suno"),
	[]byte("ElevenLabs"),
	[]byte("Eleven Labs"),
	[]byte("MusicGen"),
	[]byte("AudioCraft"),
	[]byte("ACE Studio"),
}

// aiPlusC2paMarkers is AI_META_HINTS + C2PA_MARKERS; the concatenation order
// matters because hit lists preserve needle order.
var aiPlusC2paMarkers = append(append([][]byte{}, aiMetaHints...), c2paMarkers...)

// DetectImageFormat sniffs the container format of data, returning "png",
// "jpeg", "webp" or "unknown" (mirrors detect_format()).
func DetectImageFormat(data []byte) string {
	if bytes.HasPrefix(data, pngSig) {
		return "png"
	}
	if bytes.HasPrefix(data, jpegSOI) {
		return "jpeg"
	}
	if len(data) >= 12 && bytes.Equal(data[:4], webpRIFF) && bytes.Equal(data[8:12], webpSIG) {
		return "webp"
	}
	return "unknown"
}

// ImageInspectReport mirrors the Python ImageInspectReport dataclass.
type ImageInspectReport struct {
	Path          string
	Format        string // png | jpeg | webp | unknown
	HasC2PA       bool
	HasAIMetadata bool
	Findings      []string
	Tools         map[string]interface{}
	Synthid       interface{} // nil when absent
	Notes         []string
}

// ToDict renders the report as the Python to_dict() JSON shape: keys path,
// format, has_c2pa, has_ai_metadata, findings, findings_confidence, tools,
// synthid, notes.
func (r ImageInspectReport) ToDict() map[string]interface{} {
	findings := r.Findings
	if findings == nil {
		findings = []string{}
	}
	notes := r.Notes
	if notes == nil {
		notes = []string{}
	}
	tools := r.Tools
	if tools == nil {
		tools = map[string]interface{}{}
	}
	conf := make([]string, 0, len(findings))
	for _, f := range findings {
		conf = append(conf, ClassifyFindingConfidence(f))
	}
	return map[string]interface{}{
		"path":                r.Path,
		"format":              r.Format,
		"has_c2pa":            r.HasC2PA,
		"has_ai_metadata":     r.HasAIMetadata,
		"findings":            findings,
		"findings_confidence": conf,
		"tools":               tools,
		"synthid":             r.Synthid,
		"notes":               notes,
	}
}

// containsAny mirrors the Python _contains_any: it reports which needles
// occur (case-insensitively) in blob, in needle order, using the original
// needle spelling. Python's bytes.lower() folds only ASCII A-Z, so
// asciiLowerBytes matches it exactly; bytes.ToLower would additionally fold
// non-ASCII UTF-8 runs and could create hits Python cannot produce.
func containsAny(blob []byte, needles [][]byte) []string {
	lower := asciiLowerBytes(blob)
	var found []string
	for _, n := range needles {
		if bytes.Contains(lower, asciiLowerBytes(n)) {
			found = append(found, string(n))
		}
	}
	return found
}

// asciiLowerBytes lowercases ASCII A-Z only (Python bytes.lower()).
func asciiLowerBytes(b []byte) []byte {
	out := append([]byte{}, b...)
	for i, c := range out {
		if c >= 'A' && c <= 'Z' {
			out[i] = c + ('a' - 'A')
		}
	}
	return out
}

// pyBytesRepr mirrors Python's repr() of a bytes object (e.g. b'\x89PNG').
func pyBytesRepr(b []byte) string {
	var sb strings.Builder
	sb.WriteString("b'")
	for _, c := range b {
		switch {
		case c == '\\':
			sb.WriteString(`\\`)
		case c == '\'':
			sb.WriteString(`\'`)
		case c == '\n':
			sb.WriteString(`\n`)
		case c == '\r':
			sb.WriteString(`\r`)
		case c == '\t':
			sb.WriteString(`\t`)
		case c >= 0x20 && c < 0x7f:
			sb.WriteByte(c)
		default:
			fmt.Fprintf(&sb, `\x%02x`, c)
		}
	}
	sb.WriteByte('\'')
	return sb.String()
}

// truncateUTF8 mirrors Python str[:n] (character-based truncation) without
// ever splitting a UTF-8 sequence.
func truncateUTF8(s string, n int) string {
	r := []rune(s)
	if len(r) <= n {
		return s
	}
	return string(r[:n])
}

// splitLines mirrors Python str.splitlines() for the \n / \r\n / \r cases
// that external tool output produces.
func splitLines(s string) []string {
	s = strings.ReplaceAll(s, "\r\n", "\n")
	s = strings.ReplaceAll(s, "\r", "\n")
	return strings.Split(s, "\n")
}

// sliceFirstStr returns at most the first n elements of s.
func sliceFirstStr(s []string, n int) []string {
	if len(s) > n {
		return s[:n]
	}
	return s
}

// pyFloatStr formats a float like Python's str(): 0.25 -> "0.25", 1.0 -> "1.0".
func pyFloatStr(f float64) string {
	s := strconv.FormatFloat(f, 'g', -1, 64)
	if !strings.ContainsAny(s, ".eE") {
		s += ".0"
	}
	return s
}

func inspectPNG(data []byte) (bool, bool, []string) {
	findings := []string{}
	hasC2PA := false
	hasAI := false
	if !bytes.HasPrefix(data, pngSig) {
		return false, false, []string{"not a PNG"}
	}
	pos := 8
	for pos+8 <= len(data) {
		length := int(binary.BigEndian.Uint32(data[pos : pos+4]))
		ctype := data[pos+4 : pos+8]
		chunkStart := pos + 8
		chunkEnd := chunkStart + length
		if chunkEnd+4 > len(data) {
			findings = append(findings, fmt.Sprintf("truncated chunk %s", pyBytesRepr(ctype)))
			break
		}
		payload := data[chunkStart:chunkEnd]
		// string(ctype) is exactly a latin-1 decode (byte -> rune 1:1).
		name := string(ctype)
		// Private/ancillary chunks sometimes used for JUMBF/C2PA
		if bytes.Equal(ctype, []byte("caBX")) || bytes.Equal(ctype, []byte("juMB")) || bytes.Equal(ctype, []byte("jumb")) || bytes.HasPrefix(ctype, []byte("c2")) {
			hasC2PA = true
			findings = append(findings, fmt.Sprintf("PNG chunk %s (possible C2PA container)", name))
		}
		if bytes.Equal(ctype, []byte("tEXt")) || bytes.Equal(ctype, []byte("zTXt")) || bytes.Equal(ctype, []byte("iTXt")) || bytes.Equal(ctype, []byte("eXIf")) {
			hits := containsAny(payload, aiPlusC2paMarkers)
			if len(hits) > 0 {
				hasAI = true
				for _, h := range hits {
					hl := strings.ToLower(h)
					if hl == "c2pa" || hl == "contentcredentials" || hl == "jumb" {
						hasC2PA = true
					}
				}
				findings = append(findings, fmt.Sprintf("PNG %s: %s", name, strings.Join(sliceFirstStr(hits, 8), ", ")))
			}
		}
		if bytes.Equal(ctype, []byte("IEND")) {
			break
		}
		pos = chunkEnd + 4 // skip CRC
	}
	// Whole-file scan fallback
	whole := containsAny(data, c2paMarkers)
	if len(whole) > 0 && !hasC2PA {
		hasC2PA = true
		findings = append(findings, fmt.Sprintf("byte-scan C2PA markers: %s", strings.Join(sliceFirstStr(whole, 6), ", ")))
	}
	return hasC2PA, hasAI || hasC2PA, findings
}

func inspectJPEG(data []byte) (bool, bool, []string) {
	findings := []string{}
	hasC2PA := false
	hasAI := false
	if !bytes.HasPrefix(data, jpegSOI) {
		return false, false, []string{"not a JPEG"}
	}
	i := 2
	n := len(data)
	for i+4 <= n {
		if data[i] != 0xFF {
			i++
			continue
		}
		// skip fill
		for i < n && data[i] == 0xFF {
			i++
		}
		if i >= n {
			break
		}
		marker := data[i]
		i++
		if marker == 0xD8 || marker == 0xD9 { // SOI/EOI
			continue
		}
		if marker == 0xDA { // SOS — image data follows
			break
		}
		if marker >= 0xD0 && marker <= 0xD7 { // RSTn
			continue
		}
		if i+2 > n {
			break
		}
		seglen := int(binary.BigEndian.Uint16(data[i : i+2]))
		if seglen < 2 || i+seglen > n {
			findings = append(findings, fmt.Sprintf("bad segment length at marker 0x%02X", marker))
			break
		}
		payload := data[i+2 : i+seglen]
		i += seglen

		// APP11 (0xEB) often holds JUMBF/C2PA
		if marker == 0xEB {
			hasC2PA = true
			findings = append(findings, "JPEG APP11 segment (JUMBF/C2PA common)")
		}
		if marker == 0xE1 || marker == 0xE2 || marker == 0xED || marker == 0xEE || marker == 0xEB { // APP1,2,13,14,11
			hits := containsAny(payload, aiPlusC2paMarkers)
			if len(hits) > 0 {
				hasAI = true
				for _, h := range hits {
					hl := strings.ToLower(h)
					if hl == "c2pa" || hl == "contentcredentials" || hl == "jumb" || hl == "contentauth" {
						hasC2PA = true
					}
				}
				findings = append(findings, fmt.Sprintf("JPEG APP%d: %s", int(marker)-0xE0, strings.Join(sliceFirstStr(hits, 8), ", ")))
			}
		}
	}

	whole := containsAny(data, c2paMarkers)
	if len(whole) > 0 && !hasC2PA {
		hasC2PA = true
		findings = append(findings, fmt.Sprintf("byte-scan C2PA markers: %s", strings.Join(sliceFirstStr(whole, 6), ", ")))
	}
	return hasC2PA, hasAI || hasC2PA, findings
}

type webpChunk struct {
	fourcc  []byte
	payload []byte
	padding []byte
}

func webpChunks(data []byte) ([]webpChunk, []string) {
	if DetectImageFormat(data) != "webp" {
		return nil, []string{"not a WebP"}
	}

	notes := []string{}
	declaredSize := int(binary.LittleEndian.Uint32(data[4:8]))
	if declaredSize+8 != len(data) {
		notes = append(notes, fmt.Sprintf("RIFF size mismatch: header=%d actual=%d", declaredSize+8, len(data)))
	}

	var chunks []webpChunk
	pos := 12
	for pos+8 <= len(data) {
		fourcc := data[pos : pos+4]
		length := int(binary.LittleEndian.Uint32(data[pos+4 : pos+8]))
		payloadStart := pos + 8
		payloadEnd := payloadStart + length
		paddedEnd := payloadEnd + (length & 1)
		if paddedEnd > len(data) {
			name := string(fourcc)
			notes = append(notes, fmt.Sprintf("truncated WebP chunk %s", name))
			break
		}
		chunks = append(chunks, webpChunk{fourcc, data[payloadStart:payloadEnd], data[payloadEnd:paddedEnd]})
		pos = paddedEnd
	}
	if pos != len(data) && !anyTruncated(notes) {
		notes = append(notes, fmt.Sprintf("trailing WebP bytes: %d", len(data)-pos))
	}
	return chunks, notes
}

func anyTruncated(notes []string) bool {
	for _, note := range notes {
		if strings.Contains(note, "truncated") {
			return true
		}
	}
	return false
}

func inspectWebP(data []byte) (bool, bool, []string) {
	chunks, findings := webpChunks(data)
	if len(chunks) == 0 && len(findings) == 1 && findings[0] == "not a WebP" {
		return false, false, findings
	}

	hasC2PA := false
	hasAI := false
	for _, ch := range chunks {
		name := string(ch.fourcc)
		if bytes.Equal(bytes.ToUpper(ch.fourcc), []byte("C2PA")) {
			hasC2PA = true
			hasAI = true
			findings = append(findings, "WebP C2PA chunk")
			continue
		}
		if bytes.Equal(ch.fourcc, []byte("XMP ")) || bytes.Equal(ch.fourcc, []byte("EXIF")) {
			hits := containsAny(ch.payload, aiPlusC2paMarkers)
			if len(hits) > 0 {
				hasAI = true
				for _, hit := range hits {
					hl := strings.ToLower(hit)
					if hl == "c2pa" || hl == "contentcredentials" || hl == "jumb" || hl == "contentauth" {
						hasC2PA = true
					}
				}
				findings = append(findings, fmt.Sprintf("WebP %s: %s", name, strings.Join(sliceFirstStr(hits, 8), ", ")))
			}
		}
	}
	return hasC2PA, hasAI || hasC2PA, findings
}

var protectedPNGChunks = map[string]bool{
	"IHDR": true, "IDAT": true, "IEND": true, "PLTE": true, "tRNS": true,
	"gAMA": true, "pHYs": true, "sRGB": true, "cHRM": true, "iCCP": true,
}

func stripPNG(data []byte, stripAllText bool) ([]byte, []string, error) {
	if !bytes.HasPrefix(data, pngSig) {
		return nil, nil, fmt.Errorf("not PNG")
	}
	actions := []string{}
	out := make([]byte, 0, len(data))
	out = append(out, pngSig...)
	pos := 8
	for pos+8 <= len(data) {
		length := int(binary.BigEndian.Uint32(data[pos : pos+4]))
		ctype := data[pos+4 : pos+8]
		chunkStart := pos + 8
		chunkEnd := chunkStart + length
		if chunkEnd+4 > len(data) {
			break
		}
		payload := data[chunkStart:chunkEnd]
		crcBytes := data[chunkEnd : chunkEnd+4]
		pos = chunkEnd + 4
		name := string(ctype)

		drop := false
		if bytes.Equal(ctype, []byte("eXIf")) || bytes.Equal(ctype, []byte("caBX")) || bytes.HasPrefix(ctype, []byte("c2")) {
			drop = true
			actions = append(actions, fmt.Sprintf("drop chunk %s", name))
		} else if bytes.Equal(ctype, []byte("tEXt")) || bytes.Equal(ctype, []byte("zTXt")) || bytes.Equal(ctype, []byte("iTXt")) {
			if stripAllText || len(containsAny(payload, aiPlusC2paMarkers)) > 0 {
				drop = true
				actions = append(actions, fmt.Sprintf("drop chunk %s", name))
			}
		} else if len(containsAny(append(append([]byte{}, ctype...), payload...), c2paMarkers)) > 0 && !protectedPNGChunks[string(ctype)] {
			drop = true
			actions = append(actions, fmt.Sprintf("drop chunk %s (C2PA marker in payload)", name))
		}

		if !drop {
			var hdr [4]byte
			binary.BigEndian.PutUint32(hdr[:], uint32(length))
			out = append(out, hdr[:]...)
			out = append(out, ctype...)
			out = append(out, payload...)
			out = append(out, crcBytes...)
		}
		if bytes.Equal(ctype, []byte("IEND")) {
			break
		}
	}
	if len(actions) == 0 {
		actions = append(actions, "no PNG metadata chunks removed (already clean or none matched)")
	}
	return out, actions, nil
}

func stripJPEG(data []byte, stripAllApp bool) ([]byte, []string, error) {
	if !bytes.HasPrefix(data, jpegSOI) {
		return nil, nil, fmt.Errorf("not JPEG")
	}
	actions := []string{}
	out := make([]byte, 0, len(data))
	out = append(out, jpegSOI...)
	i := 2
	n := len(data)
	for i < n {
		if data[i] != 0xFF {
			// unexpected; copy rest
			out = append(out, data[i:]...)
			actions = append(actions, "copied remainder after non-marker byte")
			break
		}
		for i < n && data[i] == 0xFF {
			i++
		}
		if i >= n {
			break
		}
		marker := data[i]
		i++

		if marker == 0xD9 { // EOI
			out = append(out, 0xFF, 0xD9)
			break
		}
		if marker == 0xD8 { // nested SOI?
			continue
		}
		if marker >= 0xD0 && marker <= 0xD7 {
			out = append(out, 0xFF, marker)
			continue
		}
		if marker == 0xDA { // SOS — copy through end
			// need length of SOS header then entropy-coded data to EOI
			if i+2 > n {
				break
			}
			_ = binary.BigEndian.Uint16(data[i : i+2])
			// Reconstruct: FF DA + rest of file
			out = append(out, 0xFF, 0xDA)
			out = append(out, data[i:]...)
			actions = append(actions, "preserved entropy-coded scan (SOS→EOF)")
			break
		}

		if i+2 > n {
			break
		}
		seglen := int(binary.BigEndian.Uint16(data[i : i+2]))
		if seglen < 2 || i+seglen > n {
			out = append(out, data[i-2:]...) // best effort
			actions = append(actions, "truncated segment; copied remainder")
			break
		}
		payload := data[i+2 : i+seglen]
		nextI := i + seglen

		// APP0 is JFIF — keep for compatibility unless full strip of all APP
		keep := false
		drop := false
		if marker >= 0xE0 && marker <= 0xEF { // APPn
			if marker == 0xEB { // APP11 JUMBF/C2PA
				drop = true
				actions = append(actions, "drop APP11 (C2PA/JUMBF)")
			} else if stripAllApp && marker != 0xE0 {
				// keep APP0 (JFIF) by default
				drop = true
				actions = append(actions, fmt.Sprintf("drop APP%d", int(marker)-0xE0))
			} else if len(containsAny(payload, aiPlusC2paMarkers)) > 0 {
				drop = true
				actions = append(actions, fmt.Sprintf("drop APP%d (AI/C2PA markers)", int(marker)-0xE0))
			} else {
				keep = true
			}
		} else if marker == 0xFE { // COM
			drop = true
			actions = append(actions, "drop COM comment")
		} else {
			keep = true
		}

		if keep && !drop {
			out = append(out, 0xFF, marker)
			out = append(out, data[i:i+seglen]...)
		}
		i = nextI
	}

	if len(actions) == 0 {
		actions = append(actions, "no JPEG APP segments removed")
	}
	return out, actions, nil
}

func stripWebP(data []byte, stripAllMetadata bool) ([]byte, []string, error) {
	chunks, notes := webpChunks(data)
	if len(chunks) == 0 && len(notes) == 1 && notes[0] == "not a WebP" {
		return nil, nil, fmt.Errorf("not WebP")
	}
	if len(notes) > 0 {
		return nil, nil, fmt.Errorf("malformed WebP: %s", strings.Join(notes, "; "))
	}

	actions := []string{}
	type keptChunk struct {
		fourcc  []byte
		payload []byte
		padding []byte
	}
	var kept []keptChunk
	removedFlags := 0
	metadataFlags := map[string]int{"ICCP": 0x20, "EXIF": 0x08, "XMP ": 0x04}

	for _, ch := range chunks {
		drop := bytes.Equal(bytes.ToUpper(ch.fourcc), []byte("C2PA"))
		if _, ok := metadataFlags[string(ch.fourcc)]; ok {
			drop = stripAllMetadata || len(containsAny(ch.payload, aiPlusC2paMarkers)) > 0
		}
		if drop {
			name := string(ch.fourcc)
			actions = append(actions, fmt.Sprintf("drop WebP chunk %s", name))
			removedFlags |= metadataFlags[string(ch.fourcc)]
		} else {
			kept = append(kept, keptChunk{ch.fourcc, ch.payload, ch.padding})
		}
	}

	body := make([]byte, 0, len(data))
	body = append(body, webpSIG...)
	for _, ch := range kept {
		payload := ch.payload
		if bytes.Equal(ch.fourcc, []byte("VP8X")) && len(payload) >= 1 && removedFlags != 0 {
			payload = append([]byte{payload[0] &^ byte(removedFlags)}, payload[1:]...)
		}
		body = append(body, ch.fourcc...)
		var sz [4]byte
		binary.LittleEndian.PutUint32(sz[:], uint32(len(payload)))
		body = append(body, sz[:]...)
		body = append(body, payload...)
		if len(payload)&1 == 1 {
			body = append(body, ch.padding...)
		}
	}

	if len(actions) == 0 {
		actions = append(actions, "no WebP metadata chunks removed (already clean or none matched)")
	}
	var sz [4]byte
	binary.LittleEndian.PutUint32(sz[:], uint32(len(body)))
	out := append([]byte{}, webpRIFF...)
	out = append(out, sz[:]...)
	out = append(out, body...)
	return out, actions, nil
}

// captResult mirrors what Python's subprocess.CompletedProcess holds plus a
// timeout flag: stdout/stderr are captured separately, code is the exit code.
type captResult struct {
	stdout   string
	stderr   string
	code     int
	timedOut bool
	err      error
}

// runCaptured mirrors subprocess.run(args, capture_output=True, text=True,
// timeout=timeoutSec, check=False, preexec_fn=...): it runs the command,
// captures stdout/stderr separately, and reports the exit code. A non-zero
// exit is NOT an error (check=False) — only spawn failures set err. On
// timeout the child is killed and timedOut is set. The POSIX-only RLIMIT
// preexec hook of the Python original is intentionally omitted so the port
// stays Windows-compatible.
func runCaptured(args []string, timeoutSec int) captResult {
	ctx, cancel := context.WithTimeout(context.Background(), time.Duration(timeoutSec)*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, args[0], args[1:]...)
	var outBuf, errBuf bytes.Buffer
	cmd.Stdout = &outBuf
	cmd.Stderr = &errBuf
	runErr := cmd.Run()
	if ctx.Err() == context.DeadlineExceeded {
		return captResult{stdout: outBuf.String(), stderr: errBuf.String(), code: -1, timedOut: true}
	}
	code := -1
	if cmd.ProcessState != nil {
		code = cmd.ProcessState.ExitCode()
	}
	if runErr != nil {
		var exitErr *exec.ExitError
		if errors.As(runErr, &exitErr) {
			// normal exit with a non-zero status — check=False keeps going
			return captResult{stdout: outBuf.String(), stderr: errBuf.String(), code: code}
		}
		// spawn failure (command not found, ...)
		return captResult{stdout: outBuf.String(), stderr: errBuf.String(), code: code, err: runErr}
	}
	return captResult{stdout: outBuf.String(), stderr: errBuf.String(), code: code}
}

// pyReprList renders a command as Python's repr() of its args list, used to
// reproduce str(subprocess.TimeoutExpired) text, e.g.
// Command '['c2patool', 'file']' timed out after 30 seconds.
func pyReprList(args []string) string {
	parts := make([]string, len(args))
	for i, a := range args {
		parts[i] = fmt.Sprintf("'%s'", a)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// pyTimeoutErr reproduces the Python error string raised by
// subprocess.run(timeout=N) on expiry.
func pyTimeoutErr(args []string, timeoutSec int) string {
	return fmt.Sprintf("Command '%s' timed out after %d seconds", pyReprList(args), timeoutSec)
}

// exifInterestingRe mirrors the exiftool interesting-line filter from the
// Python original (re.search(..., re.I)).
var exifInterestingRe = regexp.MustCompile(`(?i)c2pa|content.?credential|AIGC|digitalSource|XMP|EXIF|IPTC|jumb`)

// RunOptionalTools runs the optional external analyzers (c2patool, exiftool)
// against path and returns the tools dict, mirroring run_optional_tools().
// Non-zero tool exits are NOT errors (check=False): the c2patool dict always
// carries returncode/snippet/has_manifest and the exiftool dict always carries
// interesting_lines; only spawn failures and timeouts produce error dicts.
func RunOptionalTools(path string) map[string]interface{} {
	tools := map[string]interface{}{}

	if c2patool := Which("c2patool"); c2patool != "" {
		args := []string{c2patool, SafeArg(path)}
		res := runCaptured(args, 30)
		switch {
		case res.timedOut:
			tools["c2patool"] = map[string]interface{}{"available": true, "error": pyTimeoutErr(args, 30)}
		case res.err != nil:
			tools["c2patool"] = map[string]interface{}{"available": true, "error": res.err.Error()}
		default:
			out := res.stdout + res.stderr
			low := strings.ToLower(out) // Python str.lower() (text mode output)
			noManifest := strings.Contains(low, "no claim") || strings.Contains(low, "no jumbf")
			tools["c2patool"] = map[string]interface{}{
				"available":    true,
				"returncode":   res.code,
				"snippet":      truncateUTF8(out, 2000),
				"has_manifest": (strings.Contains(low, "claim") || strings.Contains(low, "c2pa") || strings.Contains(low, "manifest")) && !noManifest,
			}
		}
	} else {
		tools["c2patool"] = map[string]interface{}{"available": false}
	}

	if exiftool := Which("exiftool"); exiftool != "" {
		args := []string{exiftool, "-G1", "-a", "-s", SafeArg(path)}
		res := runCaptured(args, 30)
		switch {
		case res.timedOut:
			tools["exiftool"] = map[string]interface{}{"available": true, "error": pyTimeoutErr(args, 30)}
		case res.err != nil:
			tools["exiftool"] = map[string]interface{}{"available": true, "error": res.err.Error()}
		default:
			interesting := []string{}
			for _, line := range splitLines(res.stdout) {
				if exifInterestingRe.MatchString(line) {
					interesting = append(interesting, line)
				}
			}
			tools["exiftool"] = map[string]interface{}{
				"available":         true,
				"interesting_lines": sliceFirstStr(interesting, 50),
			}
		}
	} else {
		tools["exiftool"] = map[string]interface{}{"available": false}
	}

	return tools
}

// pythonExecutable stands in for Python's sys.executable used to launch the
// harness scripts: the first interpreter found on PATH (python, then python3),
// falling back to the bare command name.
func pythonExecutable() string {
	if p := Which("python"); p != "" {
		return p
	}
	if p := Which("python3"); p != "" {
		return p
	}
	return "python"
}

// venvPython returns the upstream checkout's venv interpreter path, or "".
func venvPython(upstream string) string {
	if upstream == "" {
		return ""
	}
	rel := filepath.Join(".venv", "bin", "python")
	if runtime.GOOS == "windows" {
		rel = filepath.Join(".venv", "Scripts", "python.exe")
	}
	venv := filepath.Join(upstream, rel)
	if fi, err := os.Stat(venv); err == nil && !fi.IsDir() {
		return venv
	}
	return ""
}

// ctrlregenPython mirrors _ctrlregen_python: prefer the checkout venv.
func ctrlregenPython(upstream string) string {
	if v := venvPython(upstream); v != "" {
		return v
	}
	return pythonExecutable()
}

// markdiffusionPython mirrors _markdiffusion_python: prefer the checkout venv
// when an upstream dir is configured.
func markdiffusionPython(upstream string) string {
	if v := venvPython(upstream); v != "" {
		return v
	}
	return pythonExecutable()
}

// scriptsDir mirrors the Python SCRIPTS_DIR = Path(__file__).resolve().parent
// (the directory of image_meta.py). A compiled Go binary has no __file__, so
// the repo's service/scripts directory is located by walking up from the
// executable and the working directory; the bare relative path is used as a
// last resort so the subprocess fails with a clear error rather than
// panicking.
func scriptsDir() string {
	for _, start := range []string{execDir(), workDir()} {
		if d := findScriptsDir(start); d != "" {
			return d
		}
	}
	return filepath.Join("service", "scripts")
}

func execDir() string {
	exe, err := os.Executable()
	if err != nil {
		return ""
	}
	return filepath.Dir(exe)
}

func workDir() string {
	wd, err := os.Getwd()
	if err != nil {
		return ""
	}
	return wd
}

func findScriptsDir(start string) string {
	if start == "" {
		return ""
	}
	dir := start
	for {
		cand := filepath.Join(dir, "service", "scripts")
		if fi, err := os.Stat(cand); err == nil && fi.IsDir() {
			return cand
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

// expandUser mirrors Path.expanduser() for the "~" / "~/..." forms.
func expandUser(p string) string {
	if p == "~" {
		if h, err := os.UserHomeDir(); err == nil {
			return h
		}
		return p
	}
	if strings.HasPrefix(p, "~/") || strings.HasPrefix(p, "~\\") {
		if h, err := os.UserHomeDir(); err == nil {
			return filepath.Join(h, p[2:])
		}
	}
	return p
}

// resolvePath mirrors Path.resolve(): absolute + symlinks + normalized.
func resolvePath(p string) string {
	abs, err := filepath.Abs(p)
	if err != nil {
		return p
	}
	if resolved, err := filepath.EvalSymlinks(abs); err == nil {
		return resolved
	}
	return abs
}

// parseJSONDict mirrors json.loads(stdout or "{}").
func parseJSONDict(stdout string) (map[string]interface{}, error) {
	s := stdout
	if s == "" {
		s = "{}"
	}
	var m map[string]interface{}
	if err := json.Unmarshal([]byte(s), &m); err != nil {
		return nil, err
	}
	return m, nil
}

// runSynthidScore mirrors run_synthid_score(path, upstream_dir): it returns
// nil when REVERSE_SYNTHID_DIR is not configured, the scorer JSON dict
// otherwise.
func runSynthidScore(path, upstreamDir string) map[string]interface{} {
	if upstreamDir == "" {
		upstreamDir = os.Getenv("REVERSE_SYNTHID_DIR")
	}
	if upstreamDir == "" {
		return nil
	}
	args := []string{
		pythonExecutable(),
		filepath.Join(scriptsDir(), "score_synthid.py"),
		path,
		"--upstream-dir",
		upstreamDir,
		"--json",
	}
	res := runCaptured(args, 180)
	if res.timedOut {
		return map[string]interface{}{"available": false, "error": pyTimeoutErr(args, 180)}
	}
	if res.err != nil {
		return map[string]interface{}{"available": false, "error": res.err.Error()}
	}
	if res.code == 3 {
		// scorer not configured / unavailable: callers keep "no score" default
		return nil
	}
	if res.code != 0 {
		return map[string]interface{}{"available": false, "error": truncateUTF8(strings.TrimSpace(res.stderr), 2000)}
	}
	payload, err := parseJSONDict(res.stdout)
	if err != nil {
		return map[string]interface{}{"available": false, "error": fmt.Sprintf("bad scorer JSON: %v", err)}
	}
	return payload
}

// runCtrlregenClean mirrors run_ctrlregen_clean(...): it runs the external
// clean_ctrlregen.py harness and returns its JSON payload with "available"
// set to true on success.
func runCtrlregenClean(path, output, upstreamDir string, strength float64, steps int, device string, seed *int, timeout int) map[string]interface{} {
	if upstreamDir == "" {
		upstreamDir = os.Getenv("NOAI_WATERMARK_DIR")
	}
	if upstreamDir == "" {
		return map[string]interface{}{
			"available": false,
			"error":     "CtrlRegen not configured (set NOAI_WATERMARK_DIR or pass --ctrlregen-dir)",
		}
	}
	upstream := resolvePath(expandUser(upstreamDir))
	if fi, err := os.Stat(upstream); err != nil || !fi.IsDir() {
		return map[string]interface{}{
			"available": false,
			"error":     fmt.Sprintf("CtrlRegen dir not found: %s", upstream),
		}
	}
	args := []string{
		ctrlregenPython(upstream),
		filepath.Join(scriptsDir(), "clean_ctrlregen.py"),
		path,
		"-o",
		output,
		"--upstream-dir",
		upstream,
		"--strength",
		pyFloatStr(strength),
		"--steps",
		strconv.Itoa(steps),
		"--json",
	}
	if device != "" {
		args = append(args, "--device", device)
	}
	if seed != nil {
		args = append(args, "--seed", strconv.Itoa(*seed))
	}
	res := runCaptured(args, timeout)
	if res.timedOut {
		return map[string]interface{}{"available": false, "error": fmt.Sprintf("CtrlRegen timed out after %ds", timeout)}
	}
	if res.err != nil {
		return map[string]interface{}{"available": false, "error": res.err.Error()}
	}
	if res.code != 0 {
		return map[string]interface{}{"available": false, "error": truncateUTF8(strings.TrimSpace(res.stderr), 2000)}
	}
	payload, err := parseJSONDict(res.stdout)
	if err != nil {
		return map[string]interface{}{"available": false, "error": fmt.Sprintf("bad CtrlRegen adapter JSON: %v", err)}
	}
	payload["available"] = true
	return payload
}

// runMarkdiffusionPurify mirrors run_markdiffusion_purify(...): it runs the
// external markdiffusion_harness.py "purify" subcommand and returns its JSON
// payload with "available" set to true on success.
func runMarkdiffusionPurify(path, output, upstreamDir, model, device string, strength float64, size, steps, timeout int) map[string]interface{} {
	if upstreamDir == "" {
		upstreamDir = os.Getenv("MARKDIFFUSION_DIR")
	}
	upstream := ""
	if upstreamDir != "" {
		upstream = resolvePath(expandUser(upstreamDir))
		if fi, err := os.Stat(upstream); err != nil || !fi.IsDir() {
			return map[string]interface{}{
				"available": false,
				"error":     fmt.Sprintf("MarkDiffusion dir not found: %s", upstream),
			}
		}
	}
	args := []string{
		markdiffusionPython(upstream),
		filepath.Join(scriptsDir(), "markdiffusion_harness.py"),
		"purify",
		path,
		"-o",
		output,
		"--purification-strength",
		pyFloatStr(strength),
		"--size",
		strconv.Itoa(size),
		"--steps",
		strconv.Itoa(steps),
		"--json",
	}
	if upstream != "" {
		args = append(args, "--upstream-dir", upstream)
	}
	if model != "" {
		args = append(args, "--model", model)
	}
	if device != "" {
		args = append(args, "--device", device)
	}
	res := runCaptured(args, timeout)
	if res.timedOut {
		return map[string]interface{}{"available": false, "error": fmt.Sprintf("DiffusionPurification timed out after %ds", timeout)}
	}
	if res.err != nil {
		return map[string]interface{}{"available": false, "error": res.err.Error()}
	}
	if res.code != 0 {
		return map[string]interface{}{"available": false, "error": truncateUTF8(strings.TrimSpace(res.stderr), 2000)}
	}
	payload, err := parseJSONDict(res.stdout)
	if err != nil {
		return map[string]interface{}{"available": false, "error": fmt.Sprintf("bad MarkDiffusion adapter JSON: %v", err)}
	}
	payload["available"] = true
	return payload
}

// InspectImage inspects an image file and returns the report, mirroring
// inspect_image(path, synthid_dir=None). synthidDir may be empty to fall back
// to the REVERSE_SYNTHID_DIR environment variable.
func InspectImage(path string, synthidDir string) (ImageInspectReport, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return ImageInspectReport{}, err
	}
	format := DetectImageFormat(data)
	var hasC2PA, hasAI bool
	var findings []string
	switch format {
	case "png":
		hasC2PA, hasAI, findings = inspectPNG(data)
	case "jpeg":
		hasC2PA, hasAI, findings = inspectJPEG(data)
	case "webp":
		hasC2PA, hasAI, findings = inspectWebP(data)
	default:
		hasC2PA, hasAI, findings = false, false, []string{"unsupported format (PNG/JPEG/WebP)"}
	}

	notes := []string{}
	if format == "unknown" {
		notes = append(notes, "format not fully inspected; only PNG/JPEG are supported")
	}

	tools := RunOptionalTools(path)
	if ct, ok := tools["c2patool"].(map[string]interface{}); ok {
		if hm, ok := ct["has_manifest"].(bool); ok && hm {
			hasC2PA = true
			findings = append(findings, "c2patool reports a C2PA-related manifest")
		}
	}

	return ImageInspectReport{
		Path:          path,
		Format:        format,
		HasC2PA:       hasC2PA,
		HasAIMetadata: hasAI,
		Findings:      findings,
		Tools:         tools,
		Synthid:       runSynthidScore(path, synthidDir),
		Notes:         notes,
	}, nil
}

// CleanImageOptions mirrors clean_image()'s keyword arguments. Numeric and
// boolean options use pointers so an explicitly passed zero/false is honored
// exactly like a Python kwarg: nil means "omitted" and applies the Python
// default (StripAllMetadata=true, CtrlregenStrength=0.25, CtrlregenSteps=50,
// CtrlregenTimeout=3600, MarkdiffusionStrength=0.3, MarkdiffusionSize=512,
// MarkdiffusionSteps=50, MarkdiffusionTimeout=3600). The F64Ptr/IntPtr/
// BoolPtr helpers keep call sites readable.
type CleanImageOptions struct {
	StripAllMetadata      *bool
	SynthidDir            string
	RemovePixel           string // "", "ctrlregen", "diffusion"
	CtrlregenDir          string
	CtrlregenStrength     *float64
	CtrlregenSteps        *int
	CtrlregenDevice       string
	CtrlregenSeed         *int
	CtrlregenTimeout      *int
	MarkdiffusionDir      string
	MarkdiffusionStrength *float64
	MarkdiffusionModel    string
	MarkdiffusionSize     *int
	MarkdiffusionSteps    *int
	MarkdiffusionDevice   string
	MarkdiffusionTimeout  *int
}

// BoolPtr returns a pointer to v.
func BoolPtr(v bool) *bool { return &v }

// F64Ptr returns a pointer to v.
func F64Ptr(v float64) *float64 { return &v }

// IntPtr returns a pointer to v.
func IntPtr(v int) *int { return &v }

func derefBool(p *bool, def bool) bool {
	if p != nil {
		return *p
	}
	return def
}

func derefF64(p *float64, def float64) float64 {
	if p != nil {
		return *p
	}
	return def
}

func derefInt(p *int, def int) int {
	if p != nil {
		return *p
	}
	return def
}

// errString mirrors str(pixel_removal.get('error', 'unknown error')).
func errString(v interface{}) string {
	if s, ok := v.(string); ok {
		return s
	}
	return "unknown error"
}

// CleanImage cleans metadata from the image at src, writes the result to dest
// and returns the result dict, mirroring clean_image(path, dest, **kw). The
// dict keys are: input, output, format, actions, bytes_in, bytes_out,
// still_has_c2pa, still_has_ai_metadata, post_findings, synthid_before,
// synthid_after, pixel_removal (pixel_removal is nil when no pixel removal
// was requested).
func CleanImage(src, dest string, opts CleanImageOptions) (map[string]interface{}, error) {
	// Python keyword defaults for nil fields (see CleanImageOptions).
	stripAll := derefBool(opts.StripAllMetadata, true)
	ctrlregenStrength := derefF64(opts.CtrlregenStrength, 0.25)
	ctrlregenSteps := derefInt(opts.CtrlregenSteps, 50)
	ctrlregenTimeout := derefInt(opts.CtrlregenTimeout, 3600)
	markdiffusionStrength := derefF64(opts.MarkdiffusionStrength, 0.3)
	markdiffusionSize := derefInt(opts.MarkdiffusionSize, 512)
	markdiffusionSteps := derefInt(opts.MarkdiffusionSteps, 50)
	markdiffusionTimeout := derefInt(opts.MarkdiffusionTimeout, 3600)

	synthidBefore := runSynthidScore(src, opts.SynthidDir)

	data, err := os.ReadFile(src)
	if err != nil {
		return nil, err
	}
	format := DetectImageFormat(data)

	var cleaned []byte
	var actions []string
	switch format {
	case "png":
		cleaned, actions, err = stripPNG(data, stripAll)
	case "jpeg":
		cleaned, actions, err = stripJPEG(data, stripAll)
	case "webp":
		cleaned, actions, err = stripWebP(data, stripAll)
	default:
		return nil, fmt.Errorf("unsupported format: %s", format)
	}
	if err != nil {
		return nil, err
	}
	if err := SafeWriteBytes(dest, cleaned); err != nil {
		return nil, err
	}

	if exiftool := Which("exiftool"); exiftool != "" && stripAll {
		args := []string{exiftool, "-all=", "-overwrite_original", SafeArg(dest)}
		res := runCaptured(args, 60)
		if res.timedOut {
			actions = append(actions, fmt.Sprintf("exiftool failed: %s", pyTimeoutErr(args, 60)))
		} else if res.err != nil {
			actions = append(actions, fmt.Sprintf("exiftool failed: %s", res.err.Error()))
		} else {
			actions = append(actions, "exiftool -all= pass")
		}
	}

	var pixelRemoval map[string]interface{}
	if opts.RemovePixel != "" {
		switch opts.RemovePixel {
		case "ctrlregen":
			pixelRemoval = runCtrlregenClean(dest, dest, opts.CtrlregenDir, ctrlregenStrength, ctrlregenSteps, opts.CtrlregenDevice, opts.CtrlregenSeed, ctrlregenTimeout)
			if avail, _ := pixelRemoval["available"].(bool); avail {
				actions = append(actions, fmt.Sprintf("CtrlRegen pixel removal (strength %s)", pyFloatStr(ctrlregenStrength)))
			} else {
				actions = append(actions, fmt.Sprintf("CtrlRegen pixel removal skipped: %s", errString(pixelRemoval["error"])))
			}
		case "diffusion":
			pixelRemoval = runMarkdiffusionPurify(dest, dest, opts.MarkdiffusionDir, opts.MarkdiffusionModel, opts.MarkdiffusionDevice, markdiffusionStrength, markdiffusionSize, markdiffusionSteps, markdiffusionTimeout)
			if avail, _ := pixelRemoval["available"].(bool); avail {
				actions = append(actions, fmt.Sprintf("DiffusionPurification pixel removal (strength %s)", pyFloatStr(markdiffusionStrength)))
			} else {
				actions = append(actions, fmt.Sprintf("DiffusionPurification pixel removal skipped: %s", errString(pixelRemoval["error"])))
			}
		default:
			return nil, fmt.Errorf("unknown pixel remover: %s", opts.RemovePixel)
		}
	}

	after, err := InspectImage(dest, opts.SynthidDir)
	if err != nil {
		return nil, err
	}
	fi, err := os.Stat(dest)
	if err != nil {
		return nil, err
	}

	return map[string]interface{}{
		"input":                 src,
		"output":                dest,
		"format":                format,
		"actions":               actions,
		"bytes_in":              len(data),
		"bytes_out":             fi.Size(),
		"still_has_c2pa":        after.HasC2PA,
		"still_has_ai_metadata": after.HasAIMetadata,
		"post_findings":         after.Findings,
		"synthid_before":        synthidBefore,
		"synthid_after":         after.Synthid,
		"pixel_removal":         pixelRemoval,
	}, nil
}
