// Single Source of Truth for vendor / provenance keywords.
// This file owns c2paMarkers, aiMetaHints and the derived regexes used
// across image, container, HTML, DOCX and video/audio scanners.
// Edits here propagate everywhere; other files must not redeclare these.
package cleaning

import "regexp"

// c2paMarkers lists chunk types / content patterns associated with C2PA / AI
// provenance (mirrors Python C2PA_MARKERS; values identical).
var c2paMarkers = [][]byte{
	[]byte("c2pa"),
	[]byte("C2PA"),
	[]byte("jumb"),
	[]byte("JUMB"),
	[]byte("c2ma"),
	[]byte("contentcredentials"),
	[]byte("contentauth"),
	[]byte("cai:"),
	[]byte("http://ns.adobe.com/xmp/InstanceID/"),
}

// unifiedVendorTokens is the canonical vendor/parameter token set. The slice
// order is preserved for hit-list ordering in image scans (containsAny preserves
// needle order). Includes expanded coverage for Sora / Runway / Pika / Luma /
// Veo / Nova Reel / Kling 2.x / Stable Video / Udio / Riffusion etc.
var unifiedVendorTokens = [][]byte{
	[]byte("c2pa"),
	[]byte("C2PA"),
	[]byte("contentcredentials"),
	[]byte("ContentCredentials"),
	[]byte("digitalSourceType"),
	[]byte("trainedAlgorithmicMedia"),
	[]byte("compositeWithTrainedAlgorithmicMedia"),
	[]byte("algorithmicMedia"),
	[]byte("AIGC"),
	[]byte("aigc"),
	[]byte("AI generated"),
	[]byte("Generated by"),
	[]byte("Claude"),
	[]byte("Anthropic"),
	[]byte("OpenAI"),
	[]byte("SynthID"),
	[]byte("dcterms:provenance"),
	[]byte("Midjourney"),
	[]byte("Stable Diffusion"),
	[]byte("stablediffusion"),
	[]byte("Stability AI"),
	[]byte("SDXL"),
	[]byte("ComfyUI"),
	[]byte("Automatic1111"),
	[]byte("Negative prompt:"),
	[]byte("FLUX.1"),
	[]byte("flux1"),
	[]byte("Black Forest Labs"),
	[]byte("Ideogram"),
	[]byte("Recraft"),
	[]byte("Leonardo.ai"),
	[]byte("DALL-E"),
	[]byte("DALL·E"),
	[]byte("gpt-image"),
	[]byte("Imagen"),
	[]byte("Adobe Firefly"),
	[]byte("Grok"),
	[]byte("Doubao"),
	[]byte("豆包"),
	[]byte("Jimeng"),
	[]byte("即梦"),
	[]byte("Dreamina"),
	[]byte("Hunyuan"),
	[]byte("混元"),
	[]byte("Wanx"),
	[]byte("通义万相"),
	[]byte("Kling"),
	[]byte("可灵"),
	[]byte("CogView"),
	[]byte("CogVideoX"),
	[]byte("智谱"),
	[]byte("文心一格"),
	[]byte("ERNIE-ViLG"),
	[]byte("Hailuo"),
	[]byte("海螺"),
	[]byte("Vidu"),
	[]byte("PixVerse"),
	[]byte("Suno"),
	[]byte("ElevenLabs"),
	[]byte("Eleven Labs"),
	[]byte("MusicGen"),
	[]byte("AudioCraft"),
	[]byte("ACE Studio"),
	// Expanded vendors 2026
	[]byte("Sora"),
	[]byte("Runway"),
	[]byte("Pika"),
	[]byte("Luma"),
	[]byte("Veo"),
	[]byte("Nova Reel"),
	[]byte("Stable Video"),
	[]byte("Udio"),
	[]byte("Riffusion"),
}

// aiMetaHints is the image/container shared hint table (case-insensitive
// substring over metadata payloads). It is the unified table.
var aiMetaHints = unifiedVendorTokens

// aiPlusC2paMarkers is AI_META_HINTS + C2PA_MARKERS; order: hints first.
var aiPlusC2paMarkers = append(append([][]byte{}, aiMetaHints...), c2paMarkers...)

// vendorRegexTokens are regex fragments for aiMetaNameRe / generatorAIRe.
// They cover all vendors above plus generic markers, de-duplicated for regex.
var vendorRegexTokens = []string{
	`midjourney`, `stable.?diffusion`, `stability.?ai`, `sdxl`, `comfyui`, `automatic1111`, `negative.?prompt`,
	`black.?forest`, `flux1`, `flux\.1`, `ideogram`, `recraft`, `leonardo\.ai`,
	`dall-?e`, `dall·e`, `gpt-image`, `imagen`, `adobe firefly`, `grok`,
	`doubao`, `豆包`, `jimeng`, `即梦`, `dreamina`, `hunyuan`, `混元`, `wanx`, `通义万相`,
	`kling`, `可灵`, `cogview`, `cogvideo`, `智谱`, `文心一格`, `ernie.?vilg`, `hailuo`, `海螺`, `vidu`, `pixverse`,
	`sora`, `runway`, `pika`, `luma`, `veo`, `nova.?reel`, `stable.?video`, `udio`, `riffusion`,
	`suno`, `elevenlabs`, `musicgen`, `audiocraft`, `ace.?studio`,
}

// aiMetaNameRe mirrors AI_META_NAME_RE, now derived from unified vendors.
// It is used for frontmatter values, HTML meta, SVG comments, DOCX/ODT meta.
var aiMetaNameRe = regexp.MustCompile(`(?i)generator|ai[-_ ]?generated|claude|anthropic|openai|gemini|synthid|` +
	`c2pa|content.?credential|provenance|digital.?source|aigc|` + joinTokens(vendorRegexTokens))

// generatorAIRe matches vendor names inside a generator meta tag's content.
var generatorAIRe = regexp.MustCompile(`(?i)` + joinTokens(vendorRegexTokens) + `|claude|anthropic|openai|chatgpt|gemini|synthid|copilot`)

func joinTokens(tokens []string) string {
	out := ""
	for i, t := range tokens {
		if i > 0 {
			out += "|"
		}
		out += t
	}
	return out
}
